// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxt7eZ7DE-x2tONe1ascppT8XZExsN4uk',
    appId: '1:870400386430:web:64de21c2d5bb2d4095bf2f',
    messagingSenderId: '870400386430',
    projectId: 'chat-applaction-462d3',
    authDomain: 'chat-applaction-462d3.firebaseapp.com',
    storageBucket: 'chat-applaction-462d3.appspot.com',
    measurementId: 'G-LXK22HYBM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvFf6avXIY_ICoHf1VWKPLWhbT2kew0lQ',
    appId: '1:870400386430:android:4f465ea6c1811a3895bf2f',
    messagingSenderId: '870400386430',
    projectId: 'chat-applaction-462d3',
    storageBucket: 'chat-applaction-462d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTDFbR_ZrDL1ffrYf8t3y0FXTI1inWQ4',
    appId: '1:870400386430:ios:e41c8b5cded70e5895bf2f',
    messagingSenderId: '870400386430',
    projectId: 'chat-applaction-462d3',
    storageBucket: 'chat-applaction-462d3.appspot.com',
    iosBundleId: 'com.example.chatapplaction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTDFbR_ZrDL1ffrYf8t3y0FXTI1inWQ4',
    appId: '1:870400386430:ios:264796021aadf32095bf2f',
    messagingSenderId: '870400386430',
    projectId: 'chat-applaction-462d3',
    storageBucket: 'chat-applaction-462d3.appspot.com',
    iosBundleId: 'com.example.chatapplaction.RunnerTests',
  );
}
